# Generated by Django 5.1.7 on 2025-03-07 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('sort_index', models.IntegerField(unique=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.image')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.name')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagues', models.ManyToManyField(to='matches.league')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.name')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.sport')),
            ],
        ),
    ]
