# Generated by Django 5.1.7 on 2025-03-07 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_image_sport_league_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='sort_index',
        ),
        migrations.AlterField(
            model_name='league',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.image'),
        ),
        migrations.AlterField(
            model_name='league',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_apple',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_fifa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_onefootball',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_polsat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_viaplay',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
