# Generated by Django 5.1.7 on 2025-03-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_league_sort_index_alter_league_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commentator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='matches.name'),
        ),
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.sport'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='matches.name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.sport'),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.channel_type')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('away', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_away', to='matches.team')),
                ('home', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_home', to='matches.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.league')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.channel')),
                ('commentators', models.ManyToManyField(to='matches.commentator')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.match')),
            ],
        ),
    ]
